import { createContext, useContext, useState, useEffect } from 'react';

const AdminLanguageContext = createContext();

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    blogs: 'Articles',
    multimedia: 'Multimedia',
    settings: 'Settings',
    logout: 'Logout',

    // Dashboard
    totalArticles: 'Total Articles',
    publishedArticles: 'Published',
    draftArticles: 'Drafts',
    scheduledArticles: 'Scheduled',
    totalMultimedia: 'Total Multimedia',
    podcasts: 'Podcasts',
    videos: 'Videos',
    recentActivity: 'Recent Activity',

    // Blogs
    addArticle: 'Add Article',
    editArticle: 'Edit Article',
    deleteArticle: 'Delete Article',
    articleList: 'Articles',
    title: 'Title',
    titleEnglish: 'Title (English)',
    titleAmharic: 'Title (Amharic)',
    excerpt: 'Excerpt',
    excerptEnglish: 'Excerpt (English)',
    excerptAmharic: 'Excerpt (Amharic)',
    body: 'Content',
    bodyEnglish: 'Content (English)',
    bodyAmharic: 'Content (Amharic)',
    category: 'Category',
    pillar: 'Pillar',
    pillarPolitics: 'Politics & Power',
    pillarLaw: 'Law & Governance',
    pillarSociety: 'Society & Ethics',
    tags: 'Tags',
    featuredImage: 'Featured Image',
    uploadImage: 'Upload Image',
    status: 'Status',
    draft: 'Draft',
    published: 'Published',
    scheduled: 'Scheduled',
    publishDate: 'Publish Date',
    slug: 'URL Slug',
    slugAutoGenerated: 'Auto-generated from title',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    created: 'Created',
    updated: 'Updated',

    // Multimedia
    addMultimedia: 'Add Multimedia',
    editMultimedia: 'Edit Multimedia',
    deleteMultimedia: 'Delete Multimedia',
    multimediaList: 'Multimedia',
    type: 'Type',
    audio: 'Podcast',
    video: 'Video',
    fileUrl: 'File URL',
    thumbnailUrl: 'Thumbnail URL',
    duration: 'Duration (seconds)',
    description: 'Description',
    descriptionEnglish: 'Description (English)',
    descriptionAmharic: 'Description (Amharic)',

    // Settings
    siteSettings: 'Site Settings',
    siteName: 'Site Name',
    siteDescription: 'Site Description',
    siteUrl: 'Site URL',

    // Messages
    confirmDelete: 'Are you sure you want to delete this item?',
    saved: 'Successfully saved',
    deleted: 'Successfully deleted',
    error: 'An error occurred',
    required: 'This field is required',
    invalidEmail: 'Invalid email address',
    success: 'Success',
    warning: 'Warning',
    loading: 'Loading...',
    noData: 'No data found',
    viewAll: 'View All',
  },
  am: {
    // Navigation
    dashboard: 'ዋና ገጽ',
    blogs: 'መጣጥፍ',
    multimedia: 'ሚዲያ',
    settings: 'ቅንጅቶች',
    logout: 'ወጣ',

    // Dashboard
    totalArticles: 'አጠቃላይ መጣጥፍ',
    publishedArticles: 'የታተመ',
    draftArticles: 'ረቂቅ',
    scheduledArticles: 'የታቀደ',
    totalMultimedia: 'አጠቃላይ ሚዲያ',
    podcasts: 'ፖድካስቶች',
    videos: 'ቪዲዮዎች',
    recentActivity: 'ቅርብ ጊዜ ያለ እንቅስቃሴ',

    // Blogs
    addArticle: 'መጣጥፍ ጨምር',
    editArticle: 'መጣጥፍ ያርትዑ',
    deleteArticle: 'መጣጥፍ ሰርዝ',
    articleList: 'መጣጥፎች',
    title: 'ርዕስ',
    titleEnglish: 'ርዕስ (እንግሊዝኛ)',
    titleAmharic: 'ርዕስ (አማርኛ)',
    excerpt: 'ጽሑፍ',
    excerptEnglish: 'ጽሑፍ (እንግሊዝኛ)',
    excerptAmharic: 'ጽሑፍ (አማርኛ)',
    body: 'ይዘት',
    bodyEnglish: 'ይዘት (እንግሊዝኛ)',
    bodyAmharic: 'ይዘት (አማርኛ)',
    category: 'ምድብ',
    pillar: 'ምድብ',
    pillarPolitics: 'ፖለቲካ እና ኃይል',
    pillarLaw: 'ህግ እና አስተዳደር',
    pillarSociety: 'ህብረተ-ሰብ እና ስነ-ምግባር',
    tags: 'መጨረሻ',
    featuredImage: 'ታይቶ የታወቀ ምስል',
    uploadImage: 'ምስል ይጫኑ',
    status: 'ሁኔታ',
    draft: 'ረቂቅ',
    published: 'የታተመ',
    scheduled: 'የታቀደ',
    publishDate: 'የታተመ ቀን',
    slug: 'URL',
    slugAutoGenerated: 'ከ ርዕስ በራስ-ሰር ተፈጠረ',
    save: 'ሰርጥ',
    cancel: 'ተወው',
    delete: 'ሰርዝ',
    edit: 'ያርትዑ',
    view: 'ተመልከት',
    created: 'ተፈጠረ',
    updated: 'ታሪክ ተወሰደ',

    // Multimedia
    addMultimedia: 'ሚዲያ ጨምር',
    editMultimedia: 'ሚዲያ ያርትዑ',
    deleteMultimedia: 'ሚዲያ ሰርዝ',
    multimediaList: 'ሚዲያ',
    type: 'አይነት',
    audio: 'ፖድካስት',
    video: 'ቪዲዮ',
    fileUrl: 'ፋይል URL',
    thumbnailUrl: '縮圖 URL',
    duration: 'ቆይታ (ሰከንዶች)',
    description: 'ገለጻ',
    descriptionEnglish: 'ገለጻ (እንግሊዝኛ)',
    descriptionAmharic: 'ገለጻ (አማርኛ)',

    // Settings
    siteSettings: 'የድረ-ገጹ ቅንጅቶች',
    siteName: 'የድረ-ገጹ ስም',
    siteDescription: 'የድረ-ገጹ ገለጻ',
    siteUrl: 'የድረ-ገጹ URL',

    // Messages
    confirmDelete: 'ይህን ንጥል መሰረዝ ተወዳጁት?',
    saved: 'በተሳካ ሁኔታ ተቀምጥ',
    deleted: 'በተሳካ ሁኔታ ተሰርዘ',
    error: 'ስህተት ተከስቷል',
    required: 'ይህ መስክ ተRequired ነው',
    invalidEmail: 'ልክ ያልሆነ ኢ-ሜል አድራሻ',
    success: 'ስኬት',
    warning: 'ማስጠንቀቂያ',
    loading: 'በመጫን ላይ...',
    noData: 'ምንም ውሂብ አልተገኘም',
    viewAll: 'ሁሉንም ተመልከት',
  },
};

export function AdminLanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('admin-language');
    if (saved) {
      setLanguage(saved);
    }
  }, []);

  function switchLanguage(lang) {
    if (['en', 'am'].includes(lang)) {
      setLanguage(lang);
      localStorage.setItem('admin-language', lang);
    }
  }

  function t(key) {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  }

  return (
    <AdminLanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  if (!context) {
    throw new Error('useAdminLanguage must be used within AdminLanguageProvider');
  }
  return context;
}
